# Generated by Django 5.0.3 on 2024-03-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homes'),
    ]

    operations = [
        migrations.CreateModel(
            name='homess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('discrption', models.TextField()),
                ('cetagorys', models.CharField(choices=[('M', 'Men'), ('W', 'Women')], max_length=2)),
                ('c_img', models.ImageField(upload_to='cimg')),
            ],
        ),
        migrations.DeleteModel(
            name='homes',
        ),
    ]
