# Generated by Django 5.0.3 on 2024-03-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_about_cart_introduction_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvt', models.FileField(upload_to='cimg')),
            ],
        ),
    ]
